### ISSUE TITLE
Unknown provider: eProvider <- e <- s3Directive

### ISSUE THREAD

**Issue by jgentes** [Serhioromano/angular-aws-s3-upload#4]
Thanks for the module - it looks great.

I have everything setup (properly I believe) but when I use the directive I get an Unknown Provider error. Here's the HTML block that causes the error:

```
<button class="btn btn-default" s3 options="welcome.profile.options" ng-model="welcome.profile.image">
            Select File
        </button>
```

If I remove that block, the error does not appear. Here's the error:

```
Error: [$injector:unpr] http://errors.angularjs.org/1.4.6/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20s3Directive
    at Error (native)
    at http://localhost:5000/bower_components/angular/angular.min.js:6:416
    at http://localhost:5000/bower_components/angular/angular.min.js:40:409
    at Object.d [as get] (http://localhost:5000/bower_components/angular/angular.min.js:38:394)
    at http://localhost:5000/bower_components/angular/angular.min.js:40:483
    at d (http://localhost:5000/bower_components/angular/angular.min.js:38:394)
    at Object.e [as invoke] (http://localhost:5000/bower_components/angular/angular.min.js:39:161)
    at http://localhost:5000/bower_components/angular/angular.min.js:49:472
    at m (http://localhost:5000/bower_components/angular/angular.min.js:7:322)
    at Object.<anonymous> (http://localhost:5000/bower_components/angular/angular.min.js:49:439)
```

**Comment by jgentes** [comment]
If I load the non-minified version of the file, I get a more specific file/line error:

```
TypeError: Cannot read property 'length' of undefined
    at Object.fn (angular-s3.js:76)
    at n.a.$get.n.$digest (angular.js:15759)
    at n.a.$get.n.$apply (angular.js:16030)
    at g (angular.js:10545)
    at K (angular.js:10717)
    at XMLHttpRequest.z.onload (angular.js:10658)
```

**Comment by LucasSubli** [comment]
I second this bug

**Comment by jpike88** [comment]
Either fix the issue or close the repo, you waste people's time by having a broken library

**Comment by darlanmendonca** [comment]
+1

**Comment by Serhioromano** [comment]
I have tested it and everything works fine for me. I could not reproduce this error. Please check that you generated correct policy with given PHP file.

**Comment by jgentes** [comment]
I can't confirm, I'm no longer using this library.

**Comment by Serhioromano** [comment]
Of course you don't. Who would wait more than a year for an issue response. My apologies.
